In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
def choose_direction() -> np.array:
    dirs = np.array([[0,1],[0,-1],[1,0],[-1,0]])
    return dirs[random.randrange(4)]

In [20]:
def generate_people(count):
    people = {}
    for i in range(count):
        people[i] = {}
        people[i]['coords'] = np.full(
            (1, 2),
            [random.randint(0, 2),
             random.randint(0, 2)]
        )
        people[i]['state'] = 0
    return people

In [92]:
def check_boundary(coords_to_check):
    bottom_left = [0,0]
    top_right = [4,4]
    if (coords_to_check[0] >= bottom_left[0] and 
        coords_to_check[0] <= top_right[0] and 
        coords_to_check[1] >= bottom_left[1] and 
        coords_to_check[1] <= top_right[1]):
        print("It's OK")
        return True
    print("BAD COORDS")
    return False

In [169]:
def take_step(index: int) -> None:
    new_coords = [guys[index]['coords'][-1] + choose_direction()]
    print(f"CURRENT COORDS: {guys[index]['coords']}")
    print(f"NEW COORDS? {new_coords}")
    if not check_boundary(new_coords[-1]):
        take_step(index)
    guys[index]['coords'] = np.append(guys[index]['coords'], new_coords, axis=0)

In [170]:
guy = {'coords': np.full((1,2),[0,0]), 'state': 0}
yug = {'coords': np.full((1,2),[1,1]), 'state': 1}
guys = {0:guy,1:yug}
guys

{0: {'coords': array([[0, 0]]), 'state': 0},
 1: {'coords': array([[1, 1]]), 'state': 1}}

In [171]:
print(guys[0]['coords'].shape)
print(guys[0]['coords'])

(1, 2)
[[0 0]]


In [172]:
for i in range(1):
    take_step(0)

CURRENT COORDS: [[0 0]]
NEW COORDS? [array([ 0, -1])]
BAD COORDS
CURRENT COORDS: [[0 0]]
NEW COORDS? [array([1, 0])]
It's OK


In [173]:
guys[0]

{'coords': array([[ 0,  0],
        [ 1,  0],
        [ 0, -1]]),
 'state': 0}

In [86]:
print(people[4])
for i in range(5):
    take_step(4)
print(people[4])

{'coords': array([[0, 1]]), 'state': 0}
CURRENT COORDS: [[0 1]]
NEW COORDS? [1 1]
It's OK


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [48]:
def check_contact(index: int) -> None:
    for key in people.keys():
        if key <= index:
            continue
        if np.array_equal(people[index]['coords'], people[key]['coords']):
            check_states(index, key)

In [44]:
def check_states(index: int, key: int) -> None:
    person_a = people[index]
    person_b = people[key]
    if person_a['state'] == 1 and person_b['state'] == 0:
        bite(key)
    elif person_a['state'] == 0 and person_b['state'] == 1:
        bite(index)

In [45]:
def bite(index):
    print(index)
    print("BITTEN")

In [49]:
for i in people.keys():
    check_contact(i)

2
BITTEN
3
BITTEN


In [124]:
a = np.full((1,2),[0,0])

In [125]:
a

array([[0, 0]])

In [126]:
b = np.full((1,2),[1,1])

In [138]:
np.append(a,b,axis=0)

array([[0, 0],
       [1, 1]])

array([[0, 0]])

In [31]:
# people = generate_people(5)
people[0]['state'] = 1
people

{0: {'coords': array([[2, 1]]), 'state': 1},
 1: {'coords': array([[1, 0]]), 'state': 0},
 2: {'coords': array([[2, 1]]), 'state': 0},
 3: {'coords': array([[2, 1]]), 'state': 0},
 4: {'coords': array([[0, 1]]), 'state': 0}}